const { Telegraf } = require('telegraf');
const { faker } = require('@faker-js/faker');

// আপনার টেলিগ্রাম বট টোকেন এখানে দিন
const bot = new Telegraf('8578271054:AAF8NtbAQ4pEUZpzfbNzdC8Iw-pK6BZ9Glw');

/**
 * Luhn Algorithm: কার্ড নম্বরটি বৈধ কি না তা নিশ্চিত করার জন্য
 */
function luhnChecksum(code) {
    let len = code.length;
    let parity = len % 2;
    let sum = 0;
    for (let i = 0; i < len; i++) {
        let d = parseInt(code[i]);
        if (i % 2 === parity) d *= 2;
        if (d > 9) d -= 9;
        sum += d;
    }
    return sum % 10;
}

/**
 * VCC Generator Function
 */
function generateVCC(bin) {
    let cardNumber = bin.toString();
    
    // ১৫ ডিজিট পর্যন্ত র্যান্ডম নম্বর যোগ করা
    while (cardNumber.length < 15) {
        cardNumber += Math.floor(Math.random() * 10).toString();
    }
    
    // ১৬তম ডিজিট (Check Digit) বের করা লুন অ্যালগরিদম দিয়ে
    let checksum = luhnChecksum(cardNumber + '0');
    let checkDigit = (10 - checksum) % 10;
    cardNumber += checkDigit;

    const month = String(Math.floor(Math.random() * 12) + 1).padStart(2, '0');
    const year = Math.floor(Math.random() * (2030 - 2025 + 1)) + 2025;
    const cvv = Math.floor(Math.random() * (999 - 100 + 1)) + 100;

    return { cardNumber, month, year, cvv };
}

// স্টার্ট কমান্ড
bot.start((ctx) => {
    ctx.replyWithMarkdownV2(
        '💳 *VCC Generator Bot*\n\n' +
        'ব্যবহার করতে টাইপ করুন: `/gen BIN` \n' +
        'উদাহরণ: `/gen 440393`'
    );
});

// জেনারেট কমান্ড
bot.command('gen', (ctx) => {
    const message = ctx.message.text.split(' ');
    const bin = message[1];

    if (!bin || isNaN(bin) || bin.length < 1) {
        return ctx.reply('❌ দয়া করে একটি সঠিক BIN দিন। যেমন: /gen 440393');
    }

    const card = generateVCC(bin);
    const name = faker.person.fullName();
    const country = faker.location.country();

    const response = 
        `✅ *Generated Card Details*\n` +
        `━━━━━━━━━━━━━━\n` +
        `💳 *Number:* \`${card.cardNumber}\`\n` +
        `📅 *Date:* \`${card.month}/${card.year}\`\n` +
        `🔒 *CVV:* \`${card.cvv}\`\n` +
        `👤 *Name:* ${name}\n` +
        `📍 *Country:* ${country}\n` +
        `━━━━━━━━━━━━━━\n` +
        `🔥 _Generated by Professional JS Bot_`;

    ctx.replyWithMarkdown(response);
});

// বট চালু করা
bot.launch().then(() => {
    console.log('Bot is running online...');
});

// গ্রেসফুল স্টপ
process.once('SIGINT', () => bot.stop('SIGINT'));
process.once('SIGTERM', () => bot.stop('SIGTERM'));
